

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: get the current repo
        uses: actions/checkout@v2

      - name: Deploying to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          # SOURCE_DIR: 'public' source dir on this repo
          # DEST_DIR: 'public' destination dir on S3 bucket